//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Calc/Expression.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ExpressionParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IExpressionListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.opadd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpadd([NotNull] ExpressionParser.OpaddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.opadd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpadd([NotNull] ExpressionParser.OpaddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.opsub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpsub([NotNull] ExpressionParser.OpsubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.opsub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpsub([NotNull] ExpressionParser.OpsubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.opmul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpmul([NotNull] ExpressionParser.OpmulContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.opmul"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpmul([NotNull] ExpressionParser.OpmulContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ExpressionParser.opdiv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpdiv([NotNull] ExpressionParser.OpdivContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ExpressionParser.opdiv"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpdiv([NotNull] ExpressionParser.OpdivContext context);
}
